// Banco de preguntas Trivial Nueva York — 200 preguntas
// Formato: { q: pregunta, o: [opciones], a: índice correcto (0-3), cat: categoría }

export const TRIVIA_Q = [
  // ═══ BÁSICO / GEOGRAFÍA ═══
  { q:"¿Cuántos distritos (boroughs) tiene Nueva York?", o:["3","5","7","10"], a:1, cat:"📍 Básico" },
  { q:"¿Cuál es el apodo más famoso de Nueva York?", o:["La Ciudad del Amor","La Gran Manzana","La Ciudad Eterna","La Ciudad Blanca"], a:1, cat:"📍 Básico" },
  { q:"¿Cuál de estos NO es un distrito de NY?", o:["Brooklyn","Queens","Newark","El Bronx"], a:2, cat:"📍 Básico" },
  { q:"¿Qué distrito es el más poblado de Nueva York?", o:["Manhattan","Brooklyn","Queens","El Bronx"], a:1, cat:"📍 Básico" },
  { q:"¿En qué estado de EE.UU. está la ciudad de Nueva York?", o:["Nueva Jersey","Nueva York","Connecticut","Pensilvania"], a:1, cat:"📍 Básico" },
  { q:"¿Qué río separa Manhattan de Nueva Jersey?", o:["Río Este","Río Hudson","Río Harlem","Río Bronx"], a:1, cat:"🗺️ Geografía" },
  { q:"¿Qué río separa Manhattan de Queens y Brooklyn?", o:["Río Hudson","Río Este","Río Harlem","Río Bronx"], a:1, cat:"🗺️ Geografía" },
  { q:"¿Cuál es el único distrito de NY conectado a tierra firme (no es isla)?", o:["Brooklyn","Queens","El Bronx","Staten Island"], a:2, cat:"🗺️ Geografía" },
  { q:"¿En qué isla está la mayor parte de los rascacielos de NY?", o:["Long Island","Manhattan","Staten Island","Roosevelt Island"], a:1, cat:"🗺️ Geografía" },
  { q:"¿Cómo se llama la zona financiera del sur de Manhattan?", o:["Midtown","Downtown / Financial District","Uptown","Harlem"], a:1, cat:"🗺️ Geografía" },
  { q:"¿Qué océano baña la costa de Nueva York?", o:["Pacífico","Atlántico","Índico","Ártico"], a:1, cat:"🗺️ Geografía" },
  { q:"¿Aproximadamente cuántos habitantes tiene la ciudad de NY?", o:["1 millón","8 millones","20 millones","50 millones"], a:1, cat:"🗺️ Geografía" },
  { q:"¿Qué isla pequeña está entre Manhattan y Queens, con teleférico?", o:["Ellis Island","Roosevelt Island","Liberty Island","Coney Island"], a:1, cat:"🗺️ Geografía" },
  { q:"¿Qué barrio de playa famoso está en Brooklyn?", o:["Coney Island","Rockaway","Brighton","Todos"], a:3, cat:"🗺️ Geografía" },
  { q:"¿Cómo se llama el barrio sur de Manhattan con el 9/11 Memorial?", o:["SoHo","Tribeca","Financial District","Chelsea"], a:2, cat:"🗺️ Geografía" },

  // ═══ MONUMENTOS Y LUGARES ═══
  { q:"¿Qué isla alberga la Estatua de la Libertad?", o:["Ellis Island","Liberty Island","Roosevelt Island","Staten Island"], a:1, cat:"🗽 Monumentos" },
  { q:"¿Qué país regaló la Estatua de la Libertad a EE.UU.?", o:["Reino Unido","España","Francia","Italia"], a:2, cat:"🗽 Monumentos" },
  { q:"¿En qué año se inauguró la Estatua de la Libertad?", o:["1776","1886","1920","1950"], a:1, cat:"🗽 Monumentos" },
  { q:"¿Qué lleva la Estatua de la Libertad en la mano derecha?", o:["Un libro","Una antorcha","Una espada","Una bandera"], a:1, cat:"🗽 Monumentos" },
  { q:"¿De qué color es la Estatua de la Libertad y por qué?", o:["Verde, por el óxido del cobre","Blanca, por el mármol","Dorada, por el oro","Gris, por el hierro"], a:0, cat:"🗽 Monumentos" },
  { q:"¿Qué isla fue la puerta de entrada de millones de inmigrantes?", o:["Liberty Island","Ellis Island","Roosevelt Island","Governors Island"], a:1, cat:"🗽 Monumentos" },
  { q:"¿Cómo se llama el parque más famoso de Manhattan?", o:["Hyde Park","Central Park","Prospect Park","Bryant Park"], a:1, cat:"🌳 Lugares" },
  { q:"¿Cuántas hectáreas tiene aproximadamente Central Park?", o:["50","341","1000","20"], a:1, cat:"🌳 Lugares" },
  { q:"¿Qué plaza es famosa por sus pantallas gigantes y luces?", o:["Union Square","Times Square","Herald Square","Madison Sq"], a:1, cat:"🏙️ Lugares" },
  { q:"¿Dónde se celebra la famosa fiesta de Nochevieja con la bola que cae?", o:["Central Park","Times Square","Brooklyn","Wall Street"], a:1, cat:"🏙️ Lugares" },
  { q:"¿Qué puente une Manhattan con Brooklyn y es el más famoso?", o:["Puente Brooklyn","Puente Manhattan","Williamsburg","Verrazzano"], a:0, cat:"🌉 Lugares" },
  { q:"¿En qué año se terminó el Puente de Brooklyn?", o:["1850","1883","1920","1950"], a:1, cat:"🌉 Lugares" },
  { q:"¿Qué parque elevado se construyó sobre vías de tren abandonadas?", o:["Central Park","The High Line","Bryant Park","Battery Park"], a:1, cat:"🌳 Lugares" },
  { q:"¿Cómo se llama el centro comercial y de oficinas del Rockefeller?", o:["Rockefeller Center","Times Center","Lincoln Center","Empire Center"], a:0, cat:"🏙️ Lugares" },
  { q:"¿Qué hay famoso en el Rockefeller Center en invierno?", o:["Una playa","Una pista de hielo","Un mercado de flores","Un zoo"], a:1, cat:"🏙️ Lugares" },
  { q:"¿Qué famosa biblioteca tiene dos leones de piedra en la entrada?", o:["Biblioteca del Congreso","Biblioteca Pública de NY","Biblioteca Morgan","Biblioteca Columbia"], a:1, cat:"🏛️ Lugares" },
  { q:"¿Cómo se llama el barrio bohemio famoso por sus galerías y tiendas?", o:["SoHo","Wall Street","Midtown","Harlem"], a:0, cat:"🏙️ Lugares" },
  { q:"¿Qué estación de tren tiene un techo con constelaciones pintadas?", o:["Penn Station","Grand Central","Union Station","Times Sq"], a:1, cat:"🚉 Lugares" },
  { q:"¿Qué famoso teatro de Harlem lanzó a estrellas afroamericanas?", o:["Apollo Theater","Radio City","Beacon","Bowery"], a:0, cat:"🎷 Lugares" },
  { q:"¿Qué sala de conciertos está en el Rockefeller con las Rockettes?", o:["Carnegie Hall","Radio City Music Hall","Madison Sq Garden","Beacon"], a:1, cat:"🏙️ Lugares" },
  { q:"¿Qué famoso recinto deportivo está sobre Penn Station?", o:["Yankee Stadium","Madison Square Garden","Barclays Center","Citi Field"], a:1, cat:"🏟️ Lugares" },

  // ═══ EDIFICIOS Y RASCACIELOS ═══
  { q:"¿Qué rascacielos fue el más alto del mundo hasta 1970?", o:["Chrysler Building","Empire State","One WTC","Flatiron"], a:1, cat:"🏙️ Edificios" },
  { q:"¿Cuántos pisos tiene el Empire State Building?", o:["50","102","150","200"], a:1, cat:"🏙️ Edificios" },
  { q:"¿En qué año se terminó el Empire State Building?", o:["1910","1931","1955","1970"], a:1, cat:"🏙️ Edificios" },
  { q:"¿Qué edificio art déco tiene una cúspide plateada brillante?", o:["Empire State","Chrysler Building","Flatiron","Woolworth"], a:1, cat:"🏙️ Edificios" },
  { q:"¿Qué famoso edificio tiene forma triangular o de plancha?", o:["Flatiron","Chrysler","Woolworth","Seagram"], a:0, cat:"🏙️ Edificios" },
  { q:"¿Cómo se llama el rascacielos más alto de NY hoy?", o:["Empire State","One World Trade Center","Chrysler","432 Park"], a:1, cat:"🏙️ Edificios" },
  { q:"¿Cuántos metros mide aproximadamente el One World Trade Center?", o:["200 m","541 m","800 m","1000 m"], a:1, cat:"🏙️ Edificios" },
  { q:"¿Qué edificio fue el más alto del mundo de 1913 a 1930?", o:["Woolworth Building","Empire State","Chrysler","Flatiron"], a:0, cat:"🏙️ Edificios" },
  { q:"¿Qué mirador de cristal es el más alto del hemisferio occidental?", o:["Top of the Rock","Edge (Hudson Yards)","Summit One Vanderbilt","One World"], a:1, cat:"🏙️ Edificios" },
  { q:"¿Sobre qué edificio sube King Kong en la película?", o:["Chrysler","Empire State","Woolworth","Flatiron"], a:1, cat:"🏙️ Edificios" },
  { q:"¿Qué edificio alberga la sede de las Naciones Unidas?", o:["UN Headquarters","Empire State","Chrysler","Seagram"], a:0, cat:"🏙️ Edificios" },
  { q:"¿Cómo se llama el moderno centro de transporte con forma de ave blanca?", o:["The Vessel","The Oculus","The Shed","The Edge"], a:1, cat:"🏙️ Edificios" },
  { q:"¿Cómo se llama la estructura de escaleras en forma de panal de Hudson Yards?", o:["The Vessel","The Oculus","The Shed","The Edge"], a:0, cat:"🏙️ Edificios" },

  // ═══ MUSEOS Y CULTURA ═══
  { q:"¿Cómo se llama el museo de arte más grande de NY?", o:["MoMA","Guggenheim","MET (Metropolitan)","Whitney"], a:2, cat:"🎨 Museos" },
  { q:"¿Qué museo de NY tiene una espiral blanca diseñada por Frank Lloyd Wright?", o:["MoMA","Guggenheim","MET","Whitney"], a:1, cat:"🎨 Museos" },
  { q:"¿Qué significan las siglas MoMA?", o:["Museo de Manhattan","Museo de Arte Moderno","Museo de Música","Museo Americano"], a:1, cat:"🎨 Museos" },
  { q:"¿En qué museo está el famoso esqueleto de dinosaurio de 'Noche en el Museo'?", o:["MET","Museo de Historia Natural","MoMA","Guggenheim"], a:1, cat:"🎨 Museos" },
  { q:"¿Qué museo está dedicado a un portaaviones y aviones?", o:["Intrepid","MoMA","Whitney","MET"], a:0, cat:"🎨 Museos" },
  { q:"¿En qué avenida hay tantos museos que la llaman 'Museum Mile'?", o:["Broadway","Quinta Avenida","Park Avenue","Madison"], a:1, cat:"🎨 Museos" },
  { q:"¿Qué famoso musical sobre un padre fundador triunfa en Broadway?", o:["Cats","Hamilton","Wicked","Chicago"], a:1, cat:"🎭 Cultura" },
  { q:"¿Qué barrio es el centro mundial del teatro musical?", o:["SoHo","Broadway / Theater District","Tribeca","Harlem"], a:1, cat:"🎭 Cultura" },
  { q:"¿Cómo se llaman las bailarinas famosas del Radio City?", o:["Las Vegas","Las Rockettes","Las Broadway Girls","Las NY Dolls"], a:1, cat:"🎭 Cultura" },
  { q:"¿Qué barrio es famoso por la cultura afroamericana y el jazz?", o:["Bronx","Harlem","Queens","SoHo"], a:1, cat:"🎷 Cultura" },
  { q:"¿En qué barrio nació el hip-hop en los años 70?", o:["Brooklyn","El Bronx","Harlem","Queens"], a:1, cat:"🎷 Cultura" },
  { q:"¿Qué famosa sala de conciertos clásica tiene fama mundial?", o:["Carnegie Hall","Radio City","Apollo","Beacon"], a:0, cat:"🎭 Cultura" },
  { q:"¿Qué evento LGTBI multitudinario se celebra en NY en junio?", o:["Carnaval","El Pride (Orgullo)","Halloween","Thanksgiving"], a:1, cat:"🎉 Cultura" },
  { q:"¿Qué desfile gigante organiza los grandes almacenes Macy's?", o:["Año Nuevo","Acción de Gracias (Thanksgiving)","San Patricio","Pride"], a:1, cat:"🎉 Cultura" },
  { q:"¿Qué famoso edificio de ópera está en el Lincoln Center?", o:["Metropolitan Opera","Carnegie Hall","Apollo","Radio City"], a:0, cat:"🎭 Cultura" },

  // ═══ TRANSPORTE ═══
  { q:"¿Cómo se llama el sistema de metro de NY popularmente?", o:["The Tube","The Subway","The Metro","The Underground"], a:1, cat:"🚇 Transporte" },
  { q:"¿De qué color son los típicos taxis de Nueva York?", o:["Negros","Amarillos","Blancos","Rojos"], a:1, cat:"🚕 Transporte" },
  { q:"¿Cómo se llama la estación de tren más grande de NY?", o:["Penn Station","Grand Central","Union Station","Times Sq"], a:1, cat:"🚉 Transporte" },
  { q:"¿Qué tarjeta se usa para pagar el metro y autobús de NY?", o:["Oyster","MetroCard / OMNY","Octopus","T-Money"], a:1, cat:"🚇 Transporte" },
  { q:"¿El metro de NY funciona...?", o:["Solo de día","24 horas","Solo en semana","Solo en Manhattan"], a:1, cat:"🚇 Transporte" },
  { q:"¿Qué tren conecta Nueva Jersey con Manhattan por debajo del Hudson?", o:["El AVE","El PATH","El Eurostar","El Amtrak"], a:1, cat:"🚇 Transporte" },
  { q:"¿Qué ferry gratuito ofrece vistas de la Estatua de la Libertad?", o:["Ferry de Staten Island","Ferry de Brooklyn","Ferry de Ellis","Ferry de Hudson"], a:0, cat:"⛴️ Transporte" },
  { q:"¿Cuál es el aeropuerto internacional principal de NY?", o:["LaGuardia","JFK","Newark","Todos son iguales"], a:1, cat:"✈️ Transporte" },
  { q:"¿Qué significa JFK, nombre del aeropuerto?", o:["John F. Kennedy","Just For Kids","Jersey-Florida-Kansas","John Frank King"], a:0, cat:"✈️ Transporte" },
  { q:"¿Cómo se llaman los autobuses urbanos de NY?", o:["MTA Buses","Coaches","Trams","Trolleys"], a:0, cat:"🚌 Transporte" },
  { q:"¿Qué empresa gestiona el metro y los autobuses de NY?", o:["MTA","RENFE","TfL","RATP"], a:0, cat:"🚇 Transporte" },

  // ═══ DEPORTE ═══
  { q:"¿Qué equipo de béisbol juega en el Bronx?", o:["Mets","Yankees","Dodgers","Red Sox"], a:1, cat:"⚾ Deporte" },
  { q:"¿En qué estadio juegan los Yankees?", o:["Citi Field","Yankee Stadium","Fenway","Shea"], a:1, cat:"⚾ Deporte" },
  { q:"¿Qué otro equipo de béisbol de NY juega en Queens?", o:["Yankees","Mets","Nets","Knicks"], a:1, cat:"⚾ Deporte" },
  { q:"¿Qué equipo de baloncesto NBA juega en el Madison Square Garden?", o:["Nets","Knicks","Lakers","Celtics"], a:1, cat:"🏀 Deporte" },
  { q:"¿Qué equipo NBA juega en Brooklyn?", o:["Knicks","Nets","Raptors","Sixers"], a:1, cat:"🏀 Deporte" },
  { q:"¿Qué torneo de tenis Grand Slam se juega en NY?", o:["Wimbledon","US Open","Roland Garros","Open de Australia"], a:1, cat:"🎾 Deporte" },
  { q:"¿En qué estadio se jugará la FINAL del Mundial 2026?", o:["Yankee Stadium","MetLife Stadium","Citi Field","Madison Sq"], a:1, cat:"⚽ Deporte" },
  { q:"¿En qué estado está el MetLife Stadium, sede del Mundial?", o:["Nueva York","Nueva Jersey","Connecticut","Pensilvania"], a:1, cat:"⚽ Deporte" },
  { q:"¿Qué equipo de hockey NHL juega en el Madison Square Garden?", o:["Rangers","Islanders","Devils","Bruins"], a:0, cat:"🏒 Deporte" },
  { q:"¿Qué famosa maratón recorre los 5 distritos de NY en noviembre?", o:["Maratón de NY","Maratón de Boston","Maratón de Chicago","Maratón de LA"], a:0, cat:"🏃 Deporte" },

  // ═══ CINE Y TV ═══
  { q:"¿En qué ciudad transcurre la serie 'Friends'?", o:["Los Ángeles","Nueva York","Chicago","Boston"], a:1, cat:"🎬 Cine y TV" },
  { q:"¿Qué película de dibujos tiene fantasmas y un coche por NY (1984)?", o:["Los Cazafantasmas","Men in Black","Spider-Man","Gremlins"], a:0, cat:"🎬 Cine y TV" },
  { q:"¿Qué superhéroe protege Nueva York trepando por edificios?", o:["Batman","Spider-Man","Superman","Hulk"], a:1, cat:"🎬 Cine y TV" },
  { q:"¿En qué tienda de la 5ª Avenida desayuna Audrey Hepburn?", o:["Cartier","Tiffany & Co.","Macy's","Bloomingdale's"], a:1, cat:"🎬 Cine y TV" },
  { q:"¿Qué serie sigue a 4 amigas por NY y sus zapatos?", o:["Friends","Sexo en Nueva York","Girls","Seinfeld"], a:1, cat:"🎬 Cine y TV" },
  { q:"¿En qué barrio está ambientada la película 'West Side Story'?", o:["Harlem","Upper West Side","Brooklyn","Queens"], a:1, cat:"🎬 Cine y TV" },
  { q:"¿Qué película de Spielberg sobre inmigración acaba en NY?", o:["La Terminal","E.T.","Tiburón","Hook"], a:0, cat:"🎬 Cine y TV" },
  { q:"¿Qué famoso restaurante de 'Cuando Harry encontró a Sally' está en NY?", o:["Katz's Delicatessen","McDonald's","Subway","Shake Shack"], a:0, cat:"🎬 Cine y TV" },
  { q:"¿Qué edificio aparece en la peli 'Sleepless in Seattle' (cita final)?", o:["Chrysler","Empire State","One World","Flatiron"], a:1, cat:"🎬 Cine y TV" },
  { q:"¿Qué serie de comedia de los 90 transcurría en NY sobre 'nada'?", o:["Seinfeld","Frasier","Cheers","Friends"], a:0, cat:"🎬 Cine y TV" },
  { q:"¿En qué película Kevin se pierde en NY (saga navideña)?", o:["Solo en casa 2","Elf","Gremlins","Big"], a:0, cat:"🎬 Cine y TV" },
  { q:"¿Qué película musical de 2016 empieza con un atasco... pero es en LA, no NY?", o:["La La Land","Chicago","Hairspray","Annie"], a:0, cat:"🎬 Cine y TV" },

  // ═══ COMIDA ═══
  { q:"¿Qué comida rápida es típica de los puestos callejeros de NY?", o:["Tacos","Hot dogs","Sushi","Paella"], a:1, cat:"🌭 Comida" },
  { q:"¿Qué tipo de pan con agujero es típico del desayuno neoyorquino?", o:["Croissant","Bagel","Donut","Pretzel"], a:1, cat:"🌭 Comida" },
  { q:"¿Qué pizza es famosa en NY, fina y de porciones grandes?", o:["Pizza napolitana","Pizza al estilo NY","Pizza de Chicago","Pizza romana"], a:1, cat:"🍕 Comida" },
  { q:"¿Qué dulce salado en forma de lazo se vende en la calle?", o:["Bagel","Pretzel","Donut","Muffin"], a:1, cat:"🌭 Comida" },
  { q:"¿Qué tarta de queso lleva el nombre de la ciudad?", o:["Tarta de Santiago","New York Cheesecake","Tarta Tatin","Brownie"], a:1, cat:"🍰 Comida" },
  { q:"¿Qué cadena de hamburguesas nació en un parque de Madison Square?", o:["McDonald's","Shake Shack","Five Guys","In-N-Out"], a:1, cat:"🍔 Comida" },
  { q:"¿Qué barrio es famoso por sus restaurantes italianos auténticos?", o:["Chinatown","Little Italy","Koreatown","Harlem"], a:1, cat:"🍝 Comida" },
  { q:"¿Qué mercado gastronómico famoso está en Chelsea?", o:["Chelsea Market","Eataly","Smorgasburg","Time Out"], a:0, cat:"🍝 Comida" },
  { q:"¿Qué propina se suele dejar en un restaurante de NY?", o:["Nada","5%","15-20%","50%"], a:2, cat:"💵 Comida" },
  { q:"¿Qué bebida de café grande para llevar es típica de NY?", o:["Espresso","Coffee to go","Cortado","Carajillo"], a:1, cat:"☕ Comida" },

  // ═══ HISTORIA ═══
  { q:"¿Qué memorial recuerda los atentados del 11 de septiembre?", o:["Liberty Memorial","9/11 Memorial","Freedom Park","Ground Hall"], a:1, cat:"🕊️ Historia" },
  { q:"¿En qué año ocurrieron los atentados de las Torres Gemelas?", o:["1999","2001","2005","2010"], a:1, cat:"🕊️ Historia" },
  { q:"¿Cómo se llamaban las torres destruidas en 2001?", o:["Torres Gemelas (World Trade Center)","Torres Kio","Torres Petronas","Torres Sears"], a:0, cat:"🕊️ Historia" },
  { q:"¿Qué nombre tenía Nueva York cuando era colonia holandesa?", o:["Nueva Ámsterdam","Nueva Holanda","Nueva Orange","Nueva Batavia"], a:0, cat:"🕊️ Historia" },
  { q:"¿Qué país fundó originalmente la ciudad en 1624?", o:["Inglaterra","Holanda","Francia","España"], a:1, cat:"🕊️ Historia" },
  { q:"¿En qué isla compraron los holandeses por baratijas según la leyenda?", o:["Manhattan","Staten Island","Long Island","Ellis"], a:0, cat:"🕊️ Historia" },
  { q:"¿Nueva York fue brevemente la capital de qué país?", o:["Canadá","Estados Unidos","México","Cuba"], a:1, cat:"🕊️ Historia" },
  { q:"¿Qué presidente juró su cargo en Wall Street en 1789?", o:["Lincoln","George Washington","Jefferson","Franklin"], a:1, cat:"🕊️ Historia" },
  { q:"¿Qué gran apagón dejó NY sin luz en 1977 (y otro en 2003)?", o:["El Blackout","El Brownout","El Lights Off","El Dark Day"], a:0, cat:"🕊️ Historia" },
  { q:"¿En qué calle estaba el muro que da nombre a la zona financiera?", o:["Broadway","Wall Street","Canal Street","Bleecker"], a:1, cat:"🕊️ Historia" },

  // ═══ CURIOSIDADES ═══
  { q:"¿Por qué a NY se le llama 'la ciudad que nunca duerme'?", o:["Por el ruido","Por su actividad las 24h","Por el insomnio","Por las luces"], a:1, cat:"🍎 Curiosidades" },
  { q:"¿Cuántas calles numeradas tiene aproximadamente Manhattan?", o:["Más de 200","Solo 50","Unas 100","Más de 500"], a:0, cat:"🍎 Curiosidades" },
  { q:"¿En qué dirección van las 'Streets' en Manhattan?", o:["Norte-Sur","Este-Oeste","Diagonal","Circular"], a:1, cat:"🍎 Curiosidades" },
  { q:"¿En qué dirección van las 'Avenues' en Manhattan?", o:["Norte-Sur","Este-Oeste","Diagonal","Circular"], a:0, cat:"🍎 Curiosidades" },
  { q:"¿Qué avenida cruza Manhattan en diagonal rompiendo la cuadrícula?", o:["Park Avenue","Broadway","Madison","Lexington"], a:1, cat:"🍎 Curiosidades" },
  { q:"¿Qué animal aparece en muchas alcantarillas humeantes de NY?", o:["No hay animal, es vapor","Ratas","Palomas","Mapaches"], a:0, cat:"🍎 Curiosidades" },
  { q:"¿Qué tienda de juguetes gigante es famosa en la 5ª Avenida?", o:["Toys R Us","FAO Schwarz","Hamleys","Lego Store"], a:1, cat:"🧸 Curiosidades" },
  { q:"¿Qué famoso edificio cambia el color de su cúpula según la fecha?", o:["Chrysler","Empire State","One World","Flatiron"], a:1, cat:"🍎 Curiosidades" },
  { q:"¿De qué color es el típico vaso de café griego de NY?", o:["Rojo","Azul y blanco","Verde","Negro"], a:1, cat:"🍎 Curiosidades" },
  { q:"¿Qué famosa escalera de cine está en el Bronx (Joker)?", o:["Las escaleras del Joker","Las de Rocky","Las de Exorcista","Las de Batman"], a:0, cat:"🍎 Curiosidades" },
  { q:"¿Cuántos idiomas se hablan aprox. en Queens, el distrito más diverso?", o:["10","Más de 100","Solo inglés","30"], a:1, cat:"🍎 Curiosidades" },
  { q:"¿Qué color de semáforo NO existe para peatones en NY (solo manos/figuras)?", o:["Verde clásico","Sí usan mano roja y figura blanca","Azul","Naranja"], a:1, cat:"🍎 Curiosidades" },
  { q:"¿Qué famoso barrio tiene casas de piedra rojiza llamadas 'brownstones'?", o:["Brooklyn (Brooklyn Heights)","Wall Street","Times Square","JFK"], a:0, cat:"🍎 Curiosidades" },
  { q:"¿Qué hay escondido bajo Grand Central, un secreto famoso?", o:["Un río","Andén/vía secreta (track 61)","Una cárcel","Un cine"], a:1, cat:"🍎 Curiosidades" },
  { q:"¿Qué fruta dio el apodo a la ciudad en los años 20 (jazz)?", o:["La manzana","La naranja","La cereza","La uva"], a:0, cat:"🍎 Curiosidades" },

  // ═══ COMPRAS Y BARRIOS ═══
  { q:"¿En qué avenida están las tiendas de lujo más famosas?", o:["Broadway","Quinta Avenida","Wall Street","Park Avenue"], a:1, cat:"🛍️ Compras" },
  { q:"¿Qué famosos grandes almacenes tienen escaparates legendarios en Navidad?", o:["Macy's","Walmart","Target","Costco"], a:0, cat:"🛍️ Compras" },
  { q:"¿En qué barrio están las tiendas modernas y boutiques de diseño?", o:["SoHo","Wall Street","Harlem","Bronx"], a:0, cat:"🛍️ Compras" },
  { q:"¿Qué tienda de Apple en la 5ª avenida es un cubo de cristal?", o:["Apple Fifth Avenue","Apple SoHo","Apple Times Sq","Apple Brooklyn"], a:0, cat:"🛍️ Compras" },
  { q:"¿Qué barrio es famoso por su comida y comercios chinos?", o:["Little Italy","Chinatown","Koreatown","Harlem"], a:1, cat:"🛍️ Barrios" },
  { q:"¿Qué barrio de Brooklyn es famoso por ser moderno y hipster?", o:["Williamsburg","Coney Island","Brooklyn Heights","Dumbo"], a:0, cat:"🛍️ Barrios" },
  { q:"¿Qué barrio de Brooklyn tiene las mejores vistas del puente y skyline?", o:["DUMBO","Bushwick","Flatbush","Bay Ridge"], a:0, cat:"🛍️ Barrios" },
  { q:"¿Qué barrio bohemio fue cuna de artistas y músicos como Bob Dylan?", o:["Greenwich Village","Wall Street","Midtown","Harlem"], a:0, cat:"🛍️ Barrios" },
  { q:"¿Qué barrio coreano está lleno de restaurantes y karaokes?", o:["Koreatown","Chinatown","Little Italy","Harlem"], a:0, cat:"🛍️ Barrios" },
  { q:"¿Qué famoso parque de atracciones histórico está junto al mar en Brooklyn?", o:["Coney Island","Six Flags","Luna Park de Queens","Adventureland"], a:0, cat:"🛍️ Barrios" },

  // ═══ MUNDIAL 2026 / FÚTBOL ═══
  { q:"¿En qué grupo está España en el Mundial 2026?", o:["Grupo A","Grupo H","Grupo F","Grupo C"], a:1, cat:"⚽ Mundial" },
  { q:"¿Contra qué selección NO juega España en la fase de grupos?", o:["Arabia Saudí","Uruguay","Cabo Verde","Brasil"], a:3, cat:"⚽ Mundial" },
  { q:"¿En qué estadio cercano a Jersey City hay partidos del Mundial?", o:["Yankee Stadium","MetLife Stadium","Citi Field","Soldier Field"], a:1, cat:"⚽ Mundial" },
  { q:"¿Cuántas selecciones participan en el Mundial 2026?", o:["32","48","64","24"], a:1, cat:"⚽ Mundial" },
  { q:"¿Qué tres países organizan juntos el Mundial 2026?", o:["EE.UU., México y Canadá","Solo EE.UU.","EE.UU. y Brasil","México y Canadá"], a:0, cat:"⚽ Mundial" },
  { q:"¿En qué ciudad juega España su partido contra Arabia Saudí?", o:["Nueva York","Atlanta","Miami","Dallas"], a:1, cat:"⚽ Mundial" },
  { q:"¿Dónde juega España contra Uruguay?", o:["Guadalajara (México)","Nueva York","Atlanta","Toronto"], a:0, cat:"⚽ Mundial" },
  { q:"¿En qué estadio será la FINAL del Mundial 2026?", o:["Azteca","MetLife Stadium","SoFi","Rose Bowl"], a:1, cat:"⚽ Mundial" },

  // ═══ MÁS BÁSICO / VARIADO ═══
  { q:"¿Cuál es la calle más famosa de los teatros de Broadway?", o:["Broadway","Wall Street","Canal","Bleecker"], a:0, cat:"🎭 Variado" },
  { q:"¿Qué color de cielo se ve famoso al atardecer entre rascacielos (efecto)?", o:["Manhattanhenge","Sunset Row","Sky Canyon","Golden Mile"], a:0, cat:"🍎 Variado" },
  { q:"¿Qué bahía separa NY del océano con el puente Verrazzano?", o:["Bahía de Nueva York","Bahía de Hudson","Bahía Norte","Bahía Este"], a:0, cat:"🗺️ Variado" },
  { q:"¿Qué famoso zoo está dentro de Central Park?", o:["Central Park Zoo","Bronx Zoo","Queens Zoo","Prospect Zoo"], a:0, cat:"🌳 Variado" },
  { q:"¿Cuál es el zoo más grande de NY?", o:["Central Park Zoo","Bronx Zoo","Queens Zoo","Staten Zoo"], a:1, cat:"🌳 Variado" },
  { q:"¿Qué universidad de la Ivy League está en Manhattan?", o:["Harvard","Columbia","Yale","Princeton"], a:1, cat:"🎓 Variado" },
  { q:"¿Qué famosa zona verde tiene Brooklyn similar a Central Park?", o:["Prospect Park","Hyde Park","Battery Park","Bryant Park"], a:0, cat:"🌳 Variado" },
  { q:"¿Qué catedral gótica famosa está en la Quinta Avenida?", o:["San Patricio","Notre Dame","Sagrada Familia","Westminster"], a:0, cat:"⛪ Variado" },
  { q:"¿Qué famoso parque pequeño está detrás de la Biblioteca Pública?", o:["Bryant Park","Central Park","Battery Park","Madison Sq"], a:0, cat:"🌳 Variado" },
  { q:"¿Qué famosa juguetería sale en la película 'Big' con un piano gigante?", o:["FAO Schwarz","Toys R Us","Hamleys","Disney Store"], a:0, cat:"🎬 Variado" },
  { q:"¿Qué barrio tiene el famoso arco de Washington Square?", o:["Greenwich Village","SoHo","Tribeca","Chelsea"], a:0, cat:"🍎 Variado" },
  { q:"¿Qué transporte turístico recorre la ciudad con paradas (rojo, 2 pisos)?", o:["Hop-on Hop-off bus","Tranvía","Góndola","Tren turístico"], a:0, cat:"🚌 Variado" },
  { q:"¿Qué isla tiene un faro y vistas, accesible en ferry gratis?", o:["Governors Island","Liberty","Ellis","Roosevelt"], a:0, cat:"🗺️ Variado" },
  { q:"¿Cuál es la principal estación de salida de trenes de larga distancia?", o:["Penn Station","Grand Central (cercanías)","Port Authority","JFK"], a:0, cat:"🚉 Variado" },
  { q:"¿Qué terminal de autobuses es la más grande de NY?", o:["Port Authority Bus Terminal","Penn Station","Grand Central","Union"], a:0, cat:"🚌 Variado" },
  { q:"¿Qué famosa heladería/postres tiene colas enormes en NY?", o:["Levain Bakery","Mercadona","Lidl","Carrefour"], a:0, cat:"🍰 Variado" },
  { q:"¿Qué famosa galería de arte/grafiti hubo en Queens (ya demolida)?", o:["5 Pointz","Banksy Hall","Graffiti Park","Art Alley"], a:0, cat:"🎨 Variado" },
  { q:"¿Qué calle de tiendas de electrónica y luces hay cerca de Times Square?", o:["Broadway","42nd Street","Wall Street","Canal"], a:1, cat:"🛍️ Variado" },
  { q:"¿Qué barrio tiene el meatpacking district, antiguas naves reconvertidas?", o:["Meatpacking District","Wall Street","Harlem","Bronx"], a:0, cat:"🛍️ Variado" },
  { q:"¿Qué museo de cera famoso está en Times Square?", o:["Madame Tussauds","MoMA","MET","Guggenheim"], a:0, cat:"🎨 Variado" },
  { q:"¿Qué tienda de M&M's y de caramelos hay en Times Square?", o:["M&M's World","Candy Land","Sweet NY","Sugar Hill"], a:0, cat:"🍬 Variado" },
  { q:"¿Qué famoso crucero rodea Manhattan mostrando todos sus puentes?", o:["Circle Line","Carnival","Royal NY","Hudson Cruises"], a:0, cat:"⛴️ Variado" },
  { q:"¿Qué barrio tiene el ambiente latino y dominicano al norte de Manhattan?", o:["Washington Heights","SoHo","Tribeca","Chelsea"], a:0, cat:"🍎 Variado" },
  { q:"¿Qué famoso puente peatonal y comercial cruza hacia el Oculus?", o:["Brookfield Place","Time Warner","Hudson Yards","Pier 17"], a:0, cat:"🛍️ Variado" },
  { q:"¿Qué bebida alcohólica con tomate y vodka dicen que se popularizó en NY?", o:["Bloody Mary","Mojito","Sangría","Margarita"], a:0, cat:"🍸 Variado" },
  { q:"¿Qué famoso hotel de lujo está enfrente de Central Park (sale en pelis)?", o:["The Plaza","Hilton","Holiday Inn","Ibis"], a:0, cat:"🏨 Variado" },
  { q:"¿En qué barrio está el famoso restaurante Katz's del pastrami?", o:["Lower East Side","Midtown","Harlem","Bronx"], a:0, cat:"🍝 Variado" },
  { q:"¿Qué famoso edificio de discos/conciertos está en Midtown (boxeo también)?", o:["Madison Square Garden","Barclays","Apollo","Beacon"], a:0, cat:"🏟️ Variado" },
  { q:"¿Qué color domina los uniformes de la policía de NY (NYPD)?", o:["Azul marino","Verde","Marrón","Negro"], a:0, cat:"🚓 Variado" },
  { q:"¿Qué famoso barco-museo de guerra se visita en el Hudson?", o:["USS Intrepid","Titanic","Queen Mary","Bismarck"], a:0, cat:"🚢 Variado" },

  // ═══ EXTRA ═══
  { q:"¿Qué famoso puente rojo-naranja une Brooklyn con Staten Island?", o:["Verrazzano-Narrows","Brooklyn","Manhattan","George Washington"], a:0, cat:"🌉 Extra" },
  { q:"¿Qué puente une Manhattan con Nueva Jersey por el norte?", o:["George Washington Bridge","Brooklyn","Verrazzano","Queensboro"], a:0, cat:"🌉 Extra" },
  { q:"¿Cómo se llama el famoso reloj dorado de Grand Central?", o:["El reloj de ópalo de 4 caras","Big Ben","El reloj suizo","El reloj del tiempo"], a:0, cat:"🚉 Extra" },
  { q:"¿Qué barrio fue el epicentro del movimiento beatnik en los 50?", o:["Greenwich Village","Wall Street","Midtown","Harlem"], a:0, cat:"🎷 Extra" },
  { q:"¿Qué famoso edificio de Madison Avenue es sede de publicidad (Mad Men)?", o:["Edificios de Madison Ave","Empire State","Chrysler","One World"], a:0, cat:"📺 Extra" },
  { q:"¿Qué fruta gigante de cristal corona la entrada de una tienda en 5ª Av?", o:["No hay fruta, es el cubo de Apple","Una manzana","Una naranja","Una uva"], a:0, cat:"🛍️ Extra" },
  { q:"¿Qué famoso barrio financiero tiene un toro de bronce que tocar?", o:["Wall Street (Charging Bull)","SoHo","Midtown","Chelsea"], a:0, cat:"💰 Extra" },
  { q:"¿Qué estatua de niña se enfrenta al toro de Wall Street?", o:["Fearless Girl","La sirenita","La libertad","La justicia"], a:0, cat:"💰 Extra" },
  { q:"¿Cuál es la avenida más larga de Manhattan, que la cruza entera?", o:["Broadway","Quinta","Park","Madison"], a:0, cat:"🗺️ Extra" },
  { q:"¿Qué famoso edificio verde piramidal corona el New York Life?", o:["Cúspide dorada del New York Life","Empire State","Chrysler","Woolworth"], a:0, cat:"🏙️ Extra" },
  { q:"¿En qué barrio están los almacenes y galerías de Chelsea?", o:["Chelsea (oeste de Manhattan)","Bronx","Queens","Brooklyn"], a:0, cat:"🎨 Extra" },
  { q:"¿Qué transporte acuático rápido conecta barrios por el río (amarillo)?", o:["NYC Ferry","Vaporetto","Catamarán","Hovercraft"], a:0, cat:"⛴️ Extra" },
  { q:"¿Qué famosa marca de ropa deportiva tiene tienda enorme en 5ª Av?", o:["Nike","Decathlon","Sprinter","JD"], a:0, cat:"🛍️ Extra" },
  { q:"¿Qué famoso musical de gatos estuvo décadas en Broadway?", o:["Cats","Hamilton","Wicked","Lion King"], a:0, cat:"🎭 Extra" },
  { q:"¿Qué musical de Disney sobre un león triunfa en Broadway?", o:["El Rey León","Aladdin","Frozen","Encanto"], a:0, cat:"🎭 Extra" },
  { q:"¿Qué famosa tienda de chocolate suizo está en Times Square?", o:["Hershey's / Lindt","Nestlé","Valor","Milka"], a:0, cat:"🍬 Extra" },
  { q:"¿Cuántos asientos tiene aprox. el MetLife Stadium del Mundial?", o:["20.000","82.500","150.000","40.000"], a:1, cat:"⚽ Extra" },
  { q:"¿Qué línea de metro lleva al aeropuerto JFK (con AirTrain)?", o:["Línea A / E","Línea 7","Línea L","No hay metro"], a:0, cat:"🚇 Extra" },
  { q:"¿Qué famoso parque tiene el monumento a John Lennon 'Imagine'?", o:["Central Park (Strawberry Fields)","Bryant Park","Prospect","Battery"], a:0, cat:"🌳 Extra" },
  { q:"¿Frente a qué edificio mataron a John Lennon en 1980?", o:["Edificio Dakota","Empire State","Plaza Hotel","Chelsea Hotel"], a:0, cat:"🎷 Extra" },
  { q:"¿Qué famosa zona de césped y conciertos hay en Central Park?", o:["Great Lawn / Sheep Meadow","El Retiro","Hyde Lawn","Green Field"], a:0, cat:"🌳 Extra" },
  { q:"¿Qué fría estructura de hielo monta el Bryant Park en invierno?", o:["Pista de patinaje","Iglú","Trineo","Tobogán"], a:0, cat:"🏙️ Extra" },
  { q:"¿Qué famoso delicatessen judío es conocido por el pastrami?", o:["Katz's","Subway","Pret","Greggs"], a:0, cat:"🍝 Extra" },
];

